//login
export const FETCHING_USER_LOGIN_DETAILS_SUCCESS = 'FETCHING_USER_LOGIN_DETAILS_SUCCESS';
export const FETCHING_USER_LOGIN_DETAILS_FAILED = 'FETCHING_USER_LOGIN_DETAILS_FAILED';
export const FETCHING_USER_LOGIN_DETAILS_REQUEST ='FETCHING_USER_LOGIN_DETAILS_REQUEST';
//logout
export const FETCHING_USER_LOGOUT_DETAILS_REQUEST = 'FETCHING_USER_LOGOUT_DETAILS_REQUEST';
export const FETCHING_USER_LOGOUT_DETAILS_SUCCESS = 'FETCHING_USER_LOGOUT_DETAILS_SUCCESS';
export const FETCHING_USER_LOGOUT_DETAILS_FAILED = 'FETCHING_USER_LOGOUT_DETAILS_FAILED';